<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Paths to Scan
    |--------------------------------------------------------------------------
    |
    | Define the directories that phpswag should recursively scan for
    | annotations and PHP 8 Attributes.
    |
    */
    'paths' => [
        app_path(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Output Configuration
    |--------------------------------------------------------------------------
    |
    | Specify the output path and file format ('yaml' or 'json').
    |
    */
    'output' => public_path('swagger.yaml'),
    'format' => 'yaml',

    /*
    |--------------------------------------------------------------------------
    | API Metadata Defaults
    |--------------------------------------------------------------------------
    |
    | These values are used if not defined explicitly in your docblocks or attributes.
    |
    */
    'title' => env('APP_NAME', 'Laravel API'),
    'version' => '1.0.0',
    'description' => 'Laravel API Documentation generated by phpswag',
    'host' => env('APP_URL', 'http://localhost'),

    /*
    |--------------------------------------------------------------------------
    | Caching Configuration
    |--------------------------------------------------------------------------
    |
    | Enable caching to speed up the specification generation on subsequent runs.
    |
    */
    'cache' => false,
    'cache_file' => storage_path('framework/cache/phpswag-cache'),

    /*
    |--------------------------------------------------------------------------
    | Swagger UI Settings
    |--------------------------------------------------------------------------
    |
    | Enable the built-in Swagger UI route to view your API documentation.
    |
    */
    'swagger_ui' => true,
    'swagger_ui_path' => '/api/docs',

    /*
    |--------------------------------------------------------------------------
    | Filter Unused Schemas
    |--------------------------------------------------------------------------
    |
    | When set to true, schemas that are not referenced by any route/path
    | will be filtered out from the generated specification.
    |
    */
    'filter_unused' => true,
];
