<?php

namespace PhpSwag\Bridges\Symfony\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    /**
     * Generates the configuration tree builder.
     *
     * @return TreeBuilder
     */
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('phpswag');
        /** @var \Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition $rootNode */
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->arrayNode('paths')
                    ->defaultValue(['%kernel.project_dir%/src'])
                    ->prototype('scalar')->end()
                    // @phpstan-ignore-next-line
                ->end()
                ->scalarNode('output')
                    ->defaultValue('%kernel.project_dir%/public/swagger.yaml')
                ->end()
                ->scalarNode('format')
                    ->defaultValue('yaml')
                ->end()
                ->scalarNode('title')
                    ->defaultValue('Symfony API')
                ->end()
                ->scalarNode('version')
                    ->defaultValue('1.0.0')
                ->end()
                ->scalarNode('description')
                    ->defaultValue('Symfony API Documentation generated by phpswag')
                ->end()
                ->scalarNode('host')
                    ->defaultValue('http://localhost')
                ->end()
                ->arrayNode('servers')
                    ->prototype('array')
                        ->children()
                            ->scalarNode('url')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('description')->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('contact')
                    ->children()
                        ->scalarNode('name')->end()
                        ->scalarNode('email')->end()
                        ->scalarNode('url')->end()
                    ->end()
                ->end()
                ->arrayNode('license')
                    ->children()
                        ->scalarNode('name')->end()
                        ->scalarNode('url')->end()
                    ->end()
                ->end()
                ->booleanNode('cache')
                    ->defaultFalse()
                ->end()
                ->scalarNode('cache_file')
                    ->defaultValue('%kernel.project_dir%/var/cache/phpswag-cache')
                ->end()
            ->end();

        return $treeBuilder;
    }
}
